[package]
name = "rholang-rspace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
pathmap = "0.2.2"
rholang-bytecode = { path = "../rholang-bytecode" }
rholang-process = { path = "../rholang-process" }

[lib]
name = "rholang_rspace"
path = "src/lib.rs"
